version: "3.8"

services:
  postgresql_keycloak:
    image: postgres:16
    container_name: postgresql_keycloak
    command: postgres -c 'max_connections=200'
    environment:
      #- POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=db_keycloak_username
      - POSTGRES_PASSWORD=ogÂ§d23S2/(s32h3&ff8(8]HJdx34!a
    volumes:
      - kc_auth_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    restart: always
    networks:
      - internal
  pgadmin:
    image: dpage/pgadmin4:9.10.0
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: al-alloush@outlook.com
      PGADMIN_DEFAULT_PASSWORD: cv3g53f3KdflfD!3f4dH6frFnh5d43
    volumes:
      - kc_auth_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql_keycloak
    networks:
      - internal

volumes:
  kc_auth_postgres_data:
    external: true
  kc_auth_pgadmin_data:
    external: true

networks:
  internal:
    external: true
