version: "3.8"

services:
  postgresql_db:
    image: postgres:16
    container_name: postgresql_db
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=postgres  # Default database for initialization
      - POSTGRES_USER=db_service_admin_username
      - POSTGRES_PASSWORD=ogÂ§d23S2/(s32h3&ff8(8]HJdx34!a
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d # call the initialization scripts
    ports:
      - "5436:5432"
    restart: always
    networks:
      - internal
  pgadmin:
    image: dpage/pgadmin4:9.10.0
    container_name: postgresql_db_pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: al-alloush@outlook.com
      PGADMIN_DEFAULT_PASSWORD: cv3g53f3KdflfD!3f4dH6frFnh5d43
    volumes:
      - postgres_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql_db
    networks:
      - internal

volumes:
  postgres_data:
    external: true
  postgres_pgadmin_data:

networks:
  internal:
    external: true
